Update Staff Page
VATSIM-UK/core pull request #2038
Opened 2021-01-28 23:20 UTC by LouisHacking

Informed by Matthew Wilson - He left the role of 'initial flight instructor' ~6 months ago.

2021-01-28 23:27 UTC, LouisHacking commented
Accidentally added multiple commits, sorry @CalumTowers. You already know I'm a newb!

2021-01-30 14:08 UTC, CalumTowers requested changes
Thanks @LouisHacking 
Until we consider altering the numbering (e.g. for VATUK 1 - 9) then I'd prefer to keep the order as it is.
Can we adjust this PR to just amend Matthew's role?

2021-01-30 17:20 UTC, CalumTowers approved these changes

2021-01-30 17:20 UTC, merged

2021-02-01 20:04 UTC, VATSIMUK commented
:tada: This PR is included in version 6.9.2 :tada:

The release is available on [GitHub release](https://github.com/VATSIM-UK/core/releases/tag/v6.9.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: